pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:18-alpine'
                    reuseNode true
                }
            }
            steps {
                sh '''
                    ls -la
                    node --version
                    npm --version
                    cd ./my-sample-app
                    npm ci
                    npm run build
                    ls -la
                '''
            }
        }

        stage('Test') {
            steps { 
                echo "test stage"
            }
        }
    }

    post {
        always {
            echo 'post actions' 
        }

    }
}