pipeline {
    agent any

    environment {
        NETLIFY_SITE_ID = '87d12294-07f5-43de-9ddc-5743276f79d6'
        NETLIFY_AUTH_TOKEN = credentials('netlify-token')
    }

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:18-alpine'
                    reuseNode true
                }
            }
            steps {
                sh '''
                    ls -la
                    node --version
                    npm --version
                    cd ./my-sample-app
                    npm ci
                    npm run build
                    ls -la
                '''
            }
        }

        // stage('Test') {
        //     steps { 
        //         echo "test stage"
        //     }
        // }

        stage('Deploy') {
            agent {
                docker {
                    image 'node:18-alpine'
                    reuseNode true
                }
            }
            steps {
                sh '''
                    npm install netlify-cli
                    node_modules/.bin/netlify --version
                    echo "Deploying to production. Site ID: ${NETLIFY_SITE_ID}"
                    node_modules/.bin/netlify status                    
                '''
            }
        }
    }

    post {
        always {
            echo 'post actions' 
        }
    }
}